import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import { Bounce, Fade, Zoom } from 'react-reveal'
import GetStarted from '../Buttons/GetStarted'

const NftStakingPlatformSolutions = () => {
    return (
        <div className="my-5">
            <Container>
                <Row>
                    <Col lg={7} className="m-auto">
                        
                            <div className="StartUp pt-5 mt-5">
                                <span className="BgText">Solutions</span>
                                <div className="OurServicesHeadingUl">
                                    <ul>
                                        
                                            <h2>NFT Staking Platform Solutions</h2>
                                        
                                        
                                            <p className='mb-0'>
                                                <b>Incentives:</b>
                                            </p>
                                            <p>
                                                All revenues are generated by staking the NFT and incentives will appear as long as the NFT is staked.
                                            </p>
                                            <p className='mb-0'>
                                                <b>Rewards: </b>
                                            </p>
                                            <p>
                                                The NFT staking platform will various rewards based on the NFTs staked on the platform.
                                            </p>
                                            <p className='mb-0'>
                                                <b>Airdrop: </b>
                                            </p>
                                            <p>
                                                Regular airdrop is available for the users to get the NFT staking platform to keep then evolving.
                                            </p>
                                            <p className='mb-0'>
                                                <b>Transparency: </b>
                                            </p>
                                            <p>
                                                NFT staking platforms are completely transparent to the public. This transparency helps in bettering trust-ability.
                                            </p>
                                        
                                        <Col lg="3">
                                            <GetStarted buttonClass="getStarted-btn btn btn-primary" buttonText="Get Started"
                                            ></GetStarted>
                                        </Col>
                                    </ul>
                                </div>
                            </div>
                        
                    </Col>
                    <Col lg={5} className="m-auto">
                        
                            <img
                                className="w-100 shadow"
                                src="/Assets/NftPage/NftStakingPlatformSolutions.png"
                                alt="design packages"
                            ></img>
                        
                    </Col>
                </Row>
            </Container>
        </div>
    )
}

export default NftStakingPlatformSolutions